name: Build and Release RubricaX

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Create bin directory
      run: mkdir -p bin
    
    - name: Compile Java files
      run: javac -d bin src/*.java
    
    - name: Create JAR
      run: jar cfm RubricaX.jar MANIFEST.MF -C bin .
    
    - name: Generate documentation
      run: |
        cd src
        javadoc -d ../docs *.java
    
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: RubricaX-JAR
        path: RubricaX.jar
    
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: RubricaX-Docs
        path: docs/
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          RubricaX.jar
        body: |
          ## RubricaX ${{ github.ref_name }}
          
          ### 📦 Download
          - **RubricaX.jar** - Applicazione eseguibile
          
          ### 🚀 Come usare
          ```bash
          java -jar RubricaX.jar
          ```
          
          ### 📋 Requisiti
          - Java 11 o superiore
          
          ### 🔧 Novità in questa versione
          - Correzioni di sicurezza Docker
          - Documentazione aggiornata
          - Build automatico migliorato